### ISSUE TITLE
return type and object

### ISSUE THREAD

**Issue by SeRozh** [jlaksana/UML2Code#57]
**Describe the bug**
1) The methods without return value need to accept void, not all methods return something.
2) You need to include class name as type, incase there is an attribute that is object of another class or parameter of a method is object of another class.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jlaksana** [comment]
1. You are absolutely right. Will make this change now. 
2. In standard UML, attributes that are of POJO datatypes should be reflected as a relationship. Either association, composition, or aggregation. In your classes, would you like the ability to put anything as the attribute type or keep as designed?

**Comment by SeRozh** [comment]
Hi Jonathan,
  Thank you for quick respond. I just created a small UML. Let me try a big one and I will send you feedback if anything else is necessary.
Good Luck,

Sussan Einakian, Ph.D.
Pronouns she/her/hers
Department of Computer Science and Software Engineering
California Polytechnic State University
San Luis Obispo, CA 93407
Building 14 Room 202, Phone: (805)756-7186
________________________________
